move cosign-install to the beginning
```
Error: getting Rekor public keys: creating cached local store: stat /home/runner/.sigstore/root/tuf.db: permission denied
```

I think this is caused by us downloading cosign in the Justfile when
it's not already installed